export const GETUSERS_PENDING = "users/GETUSERS_PENDING";
export const GETUSERS_FULFILLED = "users/GETUSERS_FULFILLED";
export const GETUSERS_REJECTED = "users/GETUSERS_REJECTED";

export const GETUSER_BYID_PENDING = "users/GETUSER_BYID_PENDING";
export const GETUSER_BYID_FULFILLED = "users/GETUSER_BYID_FULFILLED";
export const GETUSER_BYID_REJECTED = "users/GETUSER_BYID_REJECTED";
