export const GETALLMOVIE_PENDING = "movie/GETALLMOVIE_PENDING";
export const GETALLMOVIE_FULFILLED = "users/GETALLMOVIE_FULFILLED";
export const GETALLMOVIE_REJECTED = "users/GETALLMOVIE_REJECTED";

export const GETMOVIE_BYID_PENDING = "users/GETMOVIE_BYID_PENDING";
export const GETMOVIE_BYID_FULFILLED = "users/GETMOVIE_BYID_FULFILLED";
export const GETMOVIE_BYID_REJECTED = "users/GETMOVIE_BYID_REJECTED";
